### ISSUE TITLE
Information Pop Up

### ISSUE THREAD

**Issue by ifeife123** [dhmit/tobacco_networks#13]
Creating a pop up to display information based on the clicked node.
The information should be:

- Name
- Company
- Documents Sent
- Documents Received

Steps:
- [x] Have a dynamic window that can collapse
- [x] Make the window so it interacts with the graph nicely in the viewport
- [x] Display information on the window
- [x] Relate information to the "clicked" person
- [x] Improve formatting

**Comment by wilke0818** [comment]
The pull request about to go through meets all of these standards. The button and panel now work and are out of the way. Ryaan said that though there are some improvements that could be made, it works well enough that we should focus our efforts into other aspects of the page.
