### ISSUE TITLE
positions TextField

### ISSUE THREAD

**Issue by aqyang** [dhmit/tobacco_networks#14]
In models.py, make the positions counter into a json and then write a getter method to load the json into a TextField

Steps:
- [x] Load the positions counter into a json
- [x] Write getter get_parsed_positions to load the json into a TextField

**Comment by justdatascience** [comment]
We probably discussed this already, but are we storing positions & aliases both as Counters in the json, or do we want to store aliases just as a list (ignore counts)? 

Also used json.dumps() in import_peopledb_to_person_model() to load json correctly
