### ISSUE TITLE
Remove checklist button

### ISSUE THREAD

**Issue by wilke0818** [dhmit/tobacco_networks#19]
Remove the checklist button (and relevant code) from the page as it no longer does anything for the page.

**Comment by Crista2019** [comment]
We should try to leave in all the checklist button functionality for the time being, as it provides a helpful example for what needs to be done to update other features of the graph, e.g. size (see #23)

**Comment by ryaanahmed** [comment]
@Crista2019 -- I think I said this, but now that @ifeife123 's wired up some resize code that uses the same system, we can get rid of the checkbox stuff as soon as #12 is in.
