### ISSUE TITLE
Work on the layout of the page for resizing

### ISSUE THREAD

**Issue by wilke0818** [dhmit/tobacco_networks#20]
This comes in two main components:

- [ ] Add functionality to the code so that when a browser is resized or the webpage is opened on a different device, it looks good no matter what device it is on

**Comment by Crista2019** [comment]
This issue can be approached differently for the D3 viz component than for the other features (such as the metadata display chart) (see #23)

**Comment by ryaanahmed** [comment]
Yeah, removing the graph part of @wilke0818's comment here, as that's covered in #23.

**Comment by wilke0818** [comment]
The main functionality of the page seems to keep in tact upon resizing, so I think this issue is closed for now.
