### ISSUE TITLE
Make a PR on Name Disambiguation Person & PeopleDatabase Classes

### ISSUE THREAD

**Issue by justdatascience** [dhmit/tobacco_networks#22]
@aqyang @RaquelGarcia999 We should probably make a PR on our Person, PeopleDatabase classes, and helper functions (name_disambiguation.py and name_preprocessing.py) from an earlier commit before we transitioned into Django.

Tasks:
- [x] Add comments to the code (most have been commented but not all)
- [ ] Organize the helper functions and methods within classes
- [ ] Check TODOs and either fix them or delete unnecessary ones
- [ ] Fix PEP 8 style issues (might have to refactor code a bit because duplicated code was one of the issues)
- [ ] Make sure the code passes unittests
- [ ] Write description of what we did

**Comment by ryaanahmed** [comment]
Yes please -- important to get this work in before starting on the next phase.

**Comment by mingye-christina-wang** [comment]
done
