### ISSUE TITLE
Responsively set states of viz component size as screen size changes

### ISSUE THREAD

**Issue by Crista2019** [dhmit/tobacco_networks#23]
## Context
Right now, the height and width of the D3 graph are statically set to values in the MainView component (within frontend/src/main/main.js). This means that the graph will not resize, even if the screen dimensions change.

## Process
To address this, we should use event handlers to check whether the screen size changes and update the states related to viz dimensions if this is the case.

- [x] Change the width and height states in MainView to init at window.innerWidth and window.innerHeight instead of static values
- [x] Write a function in graph.js, following the structure of `update_graph_color()`, to update the width and height of the graph. This will be called by `config.viz_update_func` within main.js (right now this is found within the `handle_checkbox()` function)
- [x] Apply dimension state changes within `componentDidUpdate()` is the config.viz_update_func prop is equal to update_graph_size

## Expected result

The viz component dynamically changes size as screen size changes.

## Current result

Right now, I am in the process of implementing these three steps.

**Comment by ryaanahmed** [comment]
Take a look at the last couple of commits on #12 -- I think some of this is now done. One additional step:
- [ ] Recompute the center of the force sim based on the resized SVG

**Comment by ifeife123** [comment]
Pull request #32 fixes some of these issues
https://github.com/dhmit/tobacco_networks/commit/27ea5c481bd1c90a7c671d0d40127e00f5136f1c
continues discussion about ways to fix the responsiveness
