### ISSUE TITLE
Focus Issue

### ISSUE THREAD

**Issue by angcast** [dhmit/tobacco_networks#27]
There a few issues with the focus function:

- [x] When the node is dragged on top of another node, it will focus the node it is on top of instead of the current node being dragged

For example:
<img width="704" alt="Screen Shot 2019-11-01 at 2 45 53 PM" src="https://user-images.githubusercontent.com/46508885/68048151-5ca3d900-fcb6-11e9-9880-748fce3c588c.png">

VS.

<img width="761" alt="Screen Shot 2019-11-01 at 2 42 15 PM" src="https://user-images.githubusercontent.com/46508885/68048145-5ada1580-fcb6-11e9-930c-b995df652aae.png">

- [x] The graph is constantly being rendered. So, sometimes when a node is being dragged the full graph for a split second shows instead of the focus graphed. 
- [ ] Focus function doesn't work for tiny nodes

**Comment by ifeife123** [comment]
There is a lot of flickering - working on the flickering on branch remove_flicker

**Comment by ifeife123** [comment]
> The graph is constantly being rendered. So, sometimes when a node is being dragged the full graph for a split second shows instead of the focus graphed.

The reason why this happens is not because of rerendering but because of the mouseover function. Fixed by pull request #33 as it temporarily turns of the mouseover functionality

**Comment by ifeife123** [comment]
> Focus function doesn't work for tiny nodes
I'm not sure if I can see this in practice, @angcast. I think it was related to other issues that have been fixed.

**Comment by ryaanahmed** [comment]
I've encountered the nodes that are hard to mouseover as well. Might be resolved, not sure. I think that's probably that they're too small. Let's call this done for now and open a new issue if that's still a problem.

**Comment by ifeife123** [comment]
> I've encountered the nodes that are hard to mouseover as well. Might be resolved, not sure. I think that's probably that they're too small. Let's call this done for now and open a new issue if that's still a problem.

@ryaanahmed 

I just did some more digging and I think the ones that can't be moved don't relate to the size of a node but the position of the node. When it is outside of its column even though you can see it you cannot interact with it. Either a new issue is needed or it relates to the issue of the div's created for the info-panel.

**Comment by ryaanahmed** [comment]
Yeah, could be that. I'm hoping once #31 is in that we'll get to a state where we have a full-width graph, with the search bar and other controls in a top panel that do not overlap. Probably will resolve this completely.
